import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Context from "@/context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          <Toaster position="top-right" richColors expand={true} />
          {children}
        </Context>
      </body>
    </html>
  );
}
